### PR TITLE
Update `TabNavigation` component

### PR DESCRIPTION
**Pull request by mastro993**
## Short description
This PR updates the `TabNavigation` component removing the internal state for selected item

## List of changes proposed in this pull request
- Removed internal state for selected item
- Updated component page in example app

### CODE REVIEW

**Comment by CrisTofani** [comment]
Is this a duplicate PR of the already merged https://github.com/pagopa/io-app-design-system/pull/236

**Comment by mastro993** [comment]
> Is this a duplicate PR of the already merged #236 ?

That's right, I didn't notice the PR.

**Comment by mastro993** [comment]
> Is this a duplicate PR of the already merged #236 ?

Part of this yes, but there is still a problem with the internal `TabNavigation` state which should be removed

**Review by CrisTofani — APPROVED** [review]
LGTM

**Pull request merged**
